#
# makefile to compile and link the GTK+ programs
# This makefile was generated by cut-n-paste of the following:
#    gcc -Wall -g program.c  `pkg-config --cflags gtk+-3.0` -o gtk_program `pkg-config --libs gtk+-3.0`
# System changes and updates may necessitate updates to this makefile
#

GTK_INCLUDE = -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
GTK_LIB = -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
CC = gcc -g -Wall

gtk_calculator: gtk_calculator.c
	$(CC) gtk_calculator.c $(GTK_INCLUDE) -o gtk_calculator $(GTK_LIB)

clean:
	rm -f *.o *~ gtk_calculator
